---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: dask-master
  namespace: dask
rules:
- apiGroups: [ "" ]
  resources: [ "pods", "services"]
  verbs: [ "get", "list", "watch", "create", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: dask-master
  namespace: dask
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: dask-master
subjects:
- kind: ServiceAccount
  name: dask-master
  namespace: dask